name: cosmos_epub
description: EPUB reader package with great UI, easy customization and awesome features
version: 0.0.1

homepage: https://github.com/Mamasodikov/cosmos_epub

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

isar_version: &isar_version ^3.1.0+1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  screen_brightness: ^1.0.1
  epubx: ^4.0.0
  fluttertoast: ^8.2.5
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.0
  html: ^0.15.4
  flutter_widget_from_html: ^0.14.11
  flutter_widget_from_html_core: ^0.14.12
  fading_edge_scrollview: ^3.0.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: *isar_version

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/

  fonts:

    #book fonts
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya.ttf
    - family: Amazon Ember
      fonts:
        - asset: assets/fonts/Amazon-Ember-Regular.ttf
    - family: Atkinson Hyperlegible
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf
    - family: Bitter Pro
      fonts:
        - asset: assets/fonts/BitterPro-Regular.ttf
    - family: Bookerly
      fonts:
        - asset: assets/fonts/Bookerly.ttf
    - family: Droid Sans
      fonts:
        - asset: assets/fonts/DroidSans.ttf
    - family: EB Garamond
      fonts:
        - asset: assets/fonts/EBGaramond-Var.ttf
    - family: Gentium Book Plus
      fonts:
        - asset: assets/fonts/GentiumBookPlus-Regular.ttf
    - family: Halant
      fonts:
        - asset: assets/fonts/Halant-Regular.ttf
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
    - family: LinLibertine
      fonts:
        - asset: assets/fonts/LinLibertine-Regular.ttf
    - family: Literata
      fonts:
        - asset: assets/fonts/Literata-Var.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Var.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Var.ttf

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
